puts "The Students of Villains Academy"
puts "------------------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "John Doe"
puts "Verbal Kint"
puts "Nurse Ratched"
puts "The Joker"
puts "Colonel Hans Landa"
puts "Hans Gruber"
puts "Agent Smith"
puts "Saruman"
